/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Logica.Calculadora;
import Logica.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeff
 */
public class FrmCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCalculadora.class.getName());
    
    Calculadora calculadora = new Calculadora();
    
    public FrmCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResistencia = new javax.swing.JLabel();
        lblCorriente = new javax.swing.JLabel();
        txtVoltaje = new javax.swing.JTextField();
        txtResistencia = new javax.swing.JTextField();
        txtCorriente = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblCombo = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblVoltaje = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResistencia.setText("Resistencia  (Ω)");

        lblCorriente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorriente.setText("Corriente (A)");
        lblCorriente.setToolTipText("");

        txtVoltaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVoltaje.addActionListener(this::txtVoltajeActionPerformed);
        txtVoltaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVoltajeKeyTyped(evt);
            }
        });

        txtResistencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtResistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResistenciaKeyTyped(evt);
            }
        });

        txtCorriente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorriente.addActionListener(this::txtCorrienteActionPerformed);
        txtCorriente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorrienteKeyTyped(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("CALCULADORA LEY DE OHM");

        lblCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCombo.setText("Variable  a Calcular:");

        cmbOperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar una opcion", "Voltaje", "Corriente", "Resistencia" }));
        cmbOperacion.setToolTipText("");
        cmbOperacion.addItemListener(this::cmbOperacionItemStateChanged);
        cmbOperacion.addActionListener(this::cmbOperacionActionPerformed);

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");

        lblVoltaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVoltaje.setText("Voltaje (V)");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorriente)
                            .addComponent(lblResistencia))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVoltaje, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtResistencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCorriente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCombo)
                                    .addComponent(lblVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(lblCombo)
                .addGap(18, 18, 18)
                .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoltajeActionPerformed

    private void txtCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrienteActionPerformed

    private void cmbOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOperacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperacionItemStateChanged

    private void cmbOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionActionPerformed
        String opcion = cmbOperacion.getSelectedItem().toString();
        txtVoltaje.setText("");
        txtCorriente.setText("");
        txtResistencia.setText("");

        txtVoltaje.setEnabled(true);
        txtCorriente.setEnabled(true);
        txtResistencia.setEnabled(true);

        switch(opcion){
            case "Voltaje":
            txtVoltaje.setEnabled(false);
            break;

            case "Corriente":
            txtCorriente.setEnabled(false);
            break;

            case "Resistencia":
            txtResistencia.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_cmbOperacionActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {

            String opcion = cmbOperacion.getSelectedItem().toString();
            double v, i, r, resultado;

            if (opcion.equals("Voltaje")) {

                i = Double.parseDouble(txtCorriente.getText());
                r = Double.parseDouble(txtResistencia.getText());

                validar(i, r);

                resultado = calculadora.calcularVoltaje(i, r);
                txtVoltaje.setText(String.format("%.2f", resultado));

            } else if (opcion.equals("Corriente")) {

                v = Double.parseDouble(txtVoltaje.getText());
                r = Double.parseDouble(txtResistencia.getText());

                validar(v, r);

                resultado = calculadora.calcularCorriente(v, r);
                txtCorriente.setText(String.format("%.2f", resultado));

            } else if (opcion.equals("Resistencia")) {

                v = Double.parseDouble(txtVoltaje.getText());
                i = Double.parseDouble(txtCorriente.getText());

                validar(v, i);

                resultado = calculadora.calcularResistencia(v, i);
                txtResistencia.setText(String.format("%.2f", resultado));
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Ingresa solo números válidos ",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        } catch (ArithmeticException e) {

            JOptionPane.showMessageDialog(this,
                    "División entre cero detectada ",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtVoltajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoltajeKeyTyped
        if (!Validaciones.esNumero(evt)) {
            evt.consume();
        } else {
            if (txtVoltaje.getText().length() == 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtVoltajeKeyTyped

    private void txtCorrienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorrienteKeyTyped
        if (!Validaciones.esNumero(evt)) {
            evt.consume();
        } else {
            if (txtCorriente.getText().length() == 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCorrienteKeyTyped

    private void txtResistenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResistenciaKeyTyped
        if (!Validaciones.esNumero(evt)) {
            evt.consume();
        } else {
            if (txtResistencia.getText().length() == 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtResistenciaKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void validar(double a, double b) {
        if (a <= 0 || b <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Los valores deben ser mayores que cero ");
            throw new ArithmeticException();
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JLabel lblCombo;
    private javax.swing.JLabel lblCorriente;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVoltaje;
    private javax.swing.JTextField txtCorriente;
    private javax.swing.JTextField txtResistencia;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables
}
